### ISSUE TITLE
Phone number validation when update customer phone

### ISSUE THREAD

**Issue by RowanG1Bilue** [braintree/braintree_node#212] opened 2022-09-20 23:00 UTC
### General information

- SDK/Library version: "3.5.0"
-  Sandbox
- Node v17.3.0-->

### Issue description

I am unit testing the update of the Customer object, for the phone field. When looking at the Braintree spec, the phone should be 10-14 characters long, and no special characters. However, regardless of which string I enter for the phone number, the customer update results in success.

**Comment by saralvasquez** [comment] 2022-09-26 17:12
I think we're going to need some additional information. What spec are you looking at specifically?

From what the code and the docs say (https://developer.paypal.com/braintree/docs/reference/request/customer/update#phone), the phone value should be, like you said, 10-14 characters and can contain numbers, dashes, parentheses, and periods. Is this inconsistent with what you've been seeing?

**Comment by RowanG1Bilue** [comment] 2022-09-26 20:12
When I pass any value for phone number, even empty string, the update
succeeds.

**Comment by saralvasquez** [comment] 2022-09-27 21:44
Okay so you said you're unit testing the Customer object. Are you hand writing unit tests for the customer object in the SDK? 

Also are you trying to test the SDK or the API, because the SDK doesn't perform any input validation. The SDK is only responsible for putting together an API request based on your input and getting the API's responses back to you. So, as long as you give the SDK parameter keys that are expected and not deprecated, it will successfully create the request no matter the value.

**Comment by RowanG1Bilue** [comment] 2022-09-28 01:15
I was actually doing an integration test, so hitting the actual API.

**Comment by saralvasquez** [comment] 2022-09-28 18:20
Actually change of plans! I verified this behavior and I'll reach out to the appropriate team to get some clarity on this behavior. Thanks for bringing this to our attention!

**Comment by saralvasquez** [comment] 2022-10-03 22:28
Update: 
We did get confirmation that there is only a check for max number of characters for the phone number since it's not a mandatory field. The team that owns this is discussing it further and I'll update this issue when they come to a consensus on what they want to do.

**Comment by saralvasquez** [comment] 2023-08-21 17:41
Closing this issues since this involves the API and not the SDK. It is also working as designed

**Closed by saralvasquez** 2023-08-21 17:41 UTC
Labels: triaged
