### ISSUE TITLE
`transaction.sale()` throws unhandled exception when credit card is invalid

### ISSUE THREAD

**Issue by tylerhsu** [braintree/braintree_node#59] opened 2015-10-06 15:12 UTC
When submitting a sale with an invalid credit card:
```
gateway.transaction.sale({
  amount: 2000, // simulate 'processor declined' on sandbox
  options: { submitForSettlement: true },
  orderId: <id>,
  customerId: <customer_id>,
  paymentMethodToken: <token>
})
```
this exception gets thrown:
```
TypeError: Cannot read property 'apiErrorResponse' of undefined
  at .../braintree/lib/braintree/gateway.js:27:19
```

My initial efforts at debugging showed that the response handler doesn't seem to be receiving the expected arguments.  The offending function in `gateway.js`:
```
Gateway.prototype.createResponseHandler = function(attributeKlassMap, klass, callback) {
    return function(err, response) {
        console.log(err); // null
        console.log(response); // undefined
      var attributeName, unknown;
      if (err) {
        return callback(err, response);
      }
      if (response.apiErrorResponse) { // This is the line that throws the exception
        return callback(null, new ErrorResponse(response.apiErrorResponse));
      } else {
        ...
```

I've confirmed that this also happens in our production environment when submitting any bogus credit card.

It's particularly bad because the exception can't be caught in the calling context, since it's being thrown from an asynchronous block.  Thus I so far I haven't been able to come up with a way to prevent this from crashing the server.

Any ideas?

**Comment by jdlc** [comment] 2015-10-06 18:38
@tylerhsu, we were able to recreate your issue. You'll need to add a callback to catch the error. Using your sandbox example, it would look like this:
```
gateway.transaction.sale({
  amount: 2000, // simulate 'processor declined' on sandbox
  options: { submitForSettlement: true },
  orderId: <id>,
  customerId: <customer_id>,
  paymentMethodToken: <token>
}, function(err, result){
  console.log(result); // log result of sale, or something else here
})
```
Here's a [guide](https://developers.braintreepayments.com/node/guides/transactions#sale) to transaction.sale() calls.
I'm closing this issue, and if you have any additional trouble with your integration, please contact [support](https://support.braintreepayments.com). P.S. Love your avatar!

**Closed by jdlc** 2015-10-06 18:38 UTC

**Comment by tylerhsu** [comment] 2015-10-06 19:29
Passing a callback does not fix this issue:

```
gateway.transaction.sale({
  amount: 2000, // simulate 'processor declined' on sandbox
  options: { submitForSettlement: true },
  orderId: <id>,
  customerId: <customer_id>,
  paymentMethodToken: <token>
}, function(err, result){
  console.log(result); // never gets called
})
```

For simplicity I left it off my original submission, but our code does define a callback, and it never executes.  This is because the response handler in `gateway.js` halts execution before any passed-in callback gets called.  Again, from `gateway.js`:

```
Gateway.prototype.createResponseHandler = function(attributeKlassMap, klass, callback) {
    return function(err, response) {
      var attributeName, unknown;
      if (err) { // err == null here, so continue
        return callback(err, response);
      }
      if (response.apiErrorResponse) { // this throws the exception
        return callback(null, new ErrorResponse(response.apiErrorResponse)); // therefore, this never gets called
      } else {
        // and we never enter this block
        ...
```

**Comment by jdlc** [comment] 2015-10-06 20:52
@tylerhsu I apologize, I misspoke in my first response: we were unable to reproduce your error using the example you provided.
​
Github is not the best forum for debugging integrations. I would suggest contacting support with more details about your integration to diagnose this problem.

**Comment by tylerhsu** [comment] 2015-10-06 22:41
This appears to be caused by the api endpoint `POST /merchants/:id/transactions` returning invalid XML under certain circumstances.  I've emailed support@braintreepayments.com with details and examples.
