### ISSUE TITLE
Customer find not wrapped into result object

### ISSUE THREAD

**Issue by marcuspoehls** [braintree/braintree_node#60] opened 2015-12-08 08:50 UTC
Hi guys,

I’ve observed a somewhat inconsistent behavior of the responses for customer methods. The thing is, `create` and `update` will return the customer wrapped into a `result` object. Using `find` returns the customer directly.

- **Q1:** Is this behavior intended? 
- **Q2:** And if Q1=yes: why do you change the return objects between methods?

Thanks for clarifying the implementation!

**Comment by raymondberg** [comment] 2015-12-14 22:50
Hi, @marcuspoehls, thanks for the great questions. 

Q1: Yes, it is. 
Q2: There are trade offs for doing it this way, but this is a case of balancing the need to make the SDK as simple as possible for the basic use case while providing developers who touch more of the SDK with a consistent, and more customizable user experience. 

We continue to make improvements in standardizing libraries both internal to each library and between the client libraries. During major version releases we get opportunities to make behavior changes based on user feedback, including yours. I'm going to close this issue for now as it is intended behavior, but please continue to communicate constructive feedback on our docs pages, here or by [contacting Braintree support](https://support.braintreepayments.com).

**Closed by raymondberg** 2015-12-14 22:50 UTC
