### ISSUE TITLE
Cannot find module './braintree/test/credit_card_defaults'

### ISSUE THREAD

**Issue by nishtacular** [braintree/braintree_node#98] opened 2017-05-02 14:38 UTC
Hi all, I'm using the node module of braintree for my project. However, after installing I am getting the following error during runtime. Further investigation shows that the `test/` directory does not exist within the `node_modules/`. How do I resolve this issue?
```
$ yarn add braintree
yarn add v0.23.2
[1/5] 🔍  Resolving packages...
[2/5] 🚚  Fetching packages...
[3/5] 🔗  Linking dependencies...
[4/5] 📃  Building fresh packages...
[5/5] ♻️  Cleaning modules...
success Saved 1 new dependency.
└─ braintree@2.0.2
✨  Done in 10.12s.
```
**Error stack trace**
```
$ babel-node index.js
{
  "stack": [
    "Error: Cannot find module './braintree/test/credit_card_defaults'",
    "    at Function.Module._resolveFilename (module.js:470:15)",
    "    at Function.Module._load (module.js:418:25)",
    "    at Module.require (module.js:498:17)",
    "    at require (internal/module.js:20:19)",
    "    at Object.<anonymous> (/Users/Developer/Sites/node_modules/braintree/lib/braintree.js:27:26)",
    "    at Module._compile (module.js:571:32)",
    "    at Module._extensions..js (module.js:580:10)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Users/Developer/Sites/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:488:32)",
    "    at tryModuleLoad (module.js:447:12)",
    "    at Function.Module._load (module.js:439:3)",
    "    at Module.require (module.js:498:17)",
    "    at require (internal/module.js:20:19)",
    "    at Object.<anonymous> (/Users/Developer/Sites/node_modules/braintree/index.js:3:18)",
    "    at Module._compile (module.js:571:32)",
    "    at Module._extensions..js (module.js:580:10)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Users/Developer/Sites/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:488:32)",
    "    at tryModuleLoad (module.js:447:12)",
    "    at Function.Module._load (module.js:439:3)",
    "    at Module.require (module.js:498:17)",
    "    at require (internal/module.js:20:19)"
  ],
  "level": "error",
  "message": "uncaughtException: Cannot find module './braintree/test/credit_card_defaults'",
  "timestamp": "2017-05-02T14:23:18.899Z"
}
```

**Comment by crookedneighbor** [comment] 2017-05-02 14:45
It exists in `braintree/lib/braintree/test/credit_card_defaults.js`, but I'd recommend using the property on the braintree object.

```js
// this will work currently, but we in no way promise that this structure will always be the same
var creditCardDefaults = require('braintree/lib/braintree/test/credit_card_defaults.js');

// instead do this
var CreditCardDefaults = require('braintree').Test.CreditCardDefaults;
```

Is there some documentation that is instructing you to `require('braintree/test/credit_card_defaults');` ?

**Comment by nishtacular** [comment] 2017-05-02 14:53
Hey @crookedneighbor thanks for the reply. I'm not actually referencing `credit_card_defaults` anywhere. All I did was install `braintree` and then include the following code:

```
import braintree from 'braintree';

const gateway = braintree.connect({
  environment: process.env.NODE_ENV === 'production' ? braintree.Environment.Production : braintree.Environment.Sandbox,
  merchantId: process.env.BRAINTREE_ID,
  publicKey: process.env.BRAINTREE_PUBLIC,
  privateKey: process.env.BRAINTREE_PRIVATE,
});
```
Also, delving into the `node_modules/braintree/lib/braintree` shows that the `test` directory is not being installed.
```
$ ls node_modules/braintree/lib/braintree/test
ls: node_modules/braintree/lib/braintree/test: No such file or directory
```

**Comment by crookedneighbor** [comment] 2017-05-02 14:54
Thanks for the info. I'll check if yarn specifically is doing something strange.

**Comment by crookedneighbor** [comment] 2017-05-02 14:59
I can't reproduce it:

<img width="955" alt="screen shot 2017-05-02 at 9 58 49 am" src="https://cloud.githubusercontent.com/assets/2916945/25624091/059ba04c-2f1e-11e7-9697-a5ad74318a0a.png">

Can you provide an example repo and a yarn version that reproduces it?

**Comment by nishtacular** [comment] 2017-05-02 15:25
Thanks for that. I created a new directory and followed the same steps and it seems to be working. But it doesn't seem to be working in my project directory. I'm stumped, not sure how to proceed 😕

**Comment by crookedneighbor** [comment] 2017-05-02 15:29
Does the same behavior occur with `npm` instead of `yarn`? Have you tried removing the node_modules folder entirely and re-installing everything?

**Comment by nishtacular** [comment] 2017-05-02 15:38
Hey mate, yes I tried `npm` instead and it worked. Really strange 😕 

At least it is working now, appreciate all the help 🙌

**Comment by crookedneighbor** [comment] 2017-05-02 15:41
I'm not an expert on `yarn`, but I wonder if there is some kind of configuration file in your project that is messing with something. You're also one patch release behind, but I didn't see anything in the release notes that would have indicated a fix for this between version `0.23.2` and `0.23.3`.

If you figure out what the issue is, feel free to post it here.

**Comment by jaspersorrio** [comment] 2017-08-16 07:41
I got the same problem with `yarn install` however `npm install` works fine.

**Comment by crookedneighbor** [comment] 2017-08-16 12:18
@jaspersorrio If you can provide an example repo that reproduces it, we're happy to look at it.

**Comment by arvindrajnaidu** [comment] 2018-09-07 05:11
This happens because you must have run yarn clean. Remove the .yarnclean file (or modify it to remove test) and try again.

**Comment by crookedneighbor** [comment] 2018-09-07 11:34
Looks like `yarn clean` removes the test folder (even though it's nested in `lib`). We'll see about renaming the folder.

**Comment by dv5** [comment] 2018-09-27 13:34
I'm using yarn version 1.10.1 and it works ok. On older version i had a same problem.

**Comment by crookedneighbor** [comment] 2018-09-27 13:40
Since it's fixed upstream in `yarn`, I'm going to close this issue rather than changing the structure of the sdk to account for a bug in older versions of yarn.

**Closed by crookedneighbor** 2018-09-27 13:40 UTC
