### ISSUE TITLE
fake-gateway-rejected-fraud-nonce results in random accepted/failing transaction

### ISSUE THREAD

**Issue by passionkind** [braintree/braintree_node#67] opened 2016-02-26 21:09 UTC
Hi braintree-team,

I just stumbled upon a weird issue. When I use `fake-gateway-rejected-fraud-nonce` for creating a transaction via the following snippet, I sometimes receive an authorized transaction and sometimes the transaction fails as it should, which breaks my tests.

Do you have any clue why this happens?

Thanks a lot!
Bastian

``` javascript
return new Promise( (resolve, reject) => {
gateway.transaction.sale({
      amount: 25.14,
      paymentMethodNonce: 'fake-gateway-rejected-fraud-nonce',
      options: { submitForSettlement: false }
    }, (err, res) => {
      if (err) {
        log.error(`Could not create transaction via braintree.`, {paymentMethodNonce, amount, options});
        reject(err);
      } else {
        log.debug(`Payment transation via braintree successful.`, res);
        resolve(res);
      }
    })
  })
}
```

**Comment by pblesi** [comment] 2016-02-29 21:31
@passionkind Using this example: 

```
gateway.transaction.sale({
      amount: 25.14,
      paymentMethodNonce: 'fake-gateway-rejected-fraud-nonce',
      options: { submitForSettlement: false }
    }, function(err, res) {
      if (err) {
        console.log("Could not create transaction via braintree.");
      } else {
        console.log("Result success?: ", res.success); // 'false'
        console.log("Result message: ", res.message); // 'Gateway Rejected: fraud'
        console.log("Transaction status: ", res.transaction.status); // 'gateway_rejected'
        console.log("Gateway Rejection Reason: ", res.transaction.gatewayRejectionReason); // 'fraud'
        console.log("Payment transaction via braintree without errors.", res);
      }
    });
 
 ```

I was not able to reproduce your issue. Keep in mind that Fraud errors are not [exceptions](https://developers.braintreepayments.com/reference/general/exceptions/node), so you will not detect them via the error parameter in the callback. These errors are gateway level errors which you detect by inspecting the created transaction. Visit our docs to learn more about [transaction statuses](https://developers.braintreepayments.com/reference/general/statuses#transaction) and [gateway rejection reasons](https://developers.braintreepayments.com/reference/response/transaction/node#gateway_rejection_reason). I would suggest reaching out to our [support team](https://support.braintreepayments.com/) if this does not resolve your issue.

**Comment by Benew** [comment] 2017-05-11 09:40
I'm able to reproduce this issue using `gateway.customer.create(options)` with options containing a `paymentMethodNonce` with value `fake-gateway-rejected-fraud-nonce`.
This is breaking my tests too...

**Comment by Benew** [comment] 2017-05-11 09:42
Please re-open

**Comment by crookedneighbor** [comment] 2017-09-18 20:12
@Benew This is definitely not an issue with the Node SDK, so I'm going to close this issue.

If you're still having issues, please reach out to our support team: https://developers.braintreepayments.com/forms/contact

Either there is some documentation that needs to be updated, or something needs to be adjusted in Braintree's backend code (again, not something that needs to change in the SDK).

**Closed by crookedneighbor** 2017-09-18 20:12 UTC

**Comment by Benew** [comment] 2017-09-19 06:30
Clearly a back-end problem. Care to mane it bubble?

**Comment by crookedneighbor** [comment] 2017-09-19 20:52
I am still unable to reproduce with this code snippet:

```js
gateway.customer.create({
  paymentMethodNonce: 'fake-gateway-rejected-fraud-nonce'
}, function (err, response) {
  if (err) {
    console.log(err);
    return;
  }

  var card = response.customer.creditCards[0];

  gateway.transaction.sale({
    amount: '10.00',
    paymentMethodToken: card.token
  }, function (err, response) {
    if (err) {
      console.log(err);
      return;
    }

    if (response.success) {
      // should never get here because nonce used is fake-gateway-rejected-fraud-nonce
      console.log('uh oh, should not have gotten here');
    } else {
      console.log(response.transaction.status) // gateway_rejected
    }
  })
});
```

If you're still having issues, it's definitely not a problem with the Node SDK. So please contact our support team so we can get to the bottom of it.

**Comment by Benew** [comment] 2017-09-20 07:06
I am, but I won't be using braintree again. My tests break every now and then but that's not a concern really.

**Comment by oliverpool** [comment] 2018-03-08 16:40
Apparently you need to adjust the amounts as well!

In your case, it would be 5001.00 (https://developers.braintreepayments.com/reference/general/testing/php#test-amounts)

But I totally agree that the braintree documentation is awful...

**Comment by Epreuve** [comment] 2018-03-08 16:57
The reason for the Gateway rejection when using the `fake-gateway-rejected-fraud-nonce` is different than when using the amount 5001.00, as one is to replicate a rejection due to fraud rules, and the other an edge case with application status.

There is no need to use both to generate a Gateway rejected transaction, however the `fake-gateway-rejected-fraud-nonce` will not reject as expected, unless you have [fraud tools](https://articles.braintreepayments.com/guides/fraud-tools/overview) enabled on your account.

If you're having problems please feel free to open a new issue or reach out to support so we can take a look.
