### ISSUE TITLE
error: customerId.trim is not a function

### ISSUE THREAD

**Issue by mariusa** [braintree/braintree_node#105] opened 2017-07-13 16:29 UTC
### General information
* SDK/Library version: 2.2.0

### Issue description
gateway.customer.find(customerId, ...)
assumes customerId is a string. When a numeric value is passed, which worked on customers.create(), it gives error:
customerId.trim is not a function
    at CustomerGateway.find (node_modules/braintree/lib/braintree/customer_gateway.js:25:20)

**Comment by crookedneighbor** [comment] 2017-07-13 16:45
This is essentially a duplicate of https://github.com/braintree/braintree_node/issues/75

Short version is that the only reason customer create works with a number is that it is [coerced into a string when constructing the url for the request](https://github.com/braintree/braintree_node/blob/b651428b576eb6b5a1e11a5b36ceb42eaabcef8b/lib/braintree/customer_gateway.js#L17). This is incidental, the documentation for [create](https://developers.braintreepayments.com/reference/request/customer/create/node#id) and [find](https://developers.braintreepayments.com/reference/request/customer/find/node#arg.customer_id) both indicate that the value passed in should be a string and we do not do any validation on the type that is passed in.

**Closed by crookedneighbor** 2017-07-13 16:45 UTC
