### ISSUE TITLE
Subscription id must not start with a number

### ISSUE THREAD

**Issue by SimoneGianni** [braintree/braintree_node#69] opened 2016-02-29 18:53 UTC
Probably this is not directly node related, but it seems like if I try to create a subscription using an ID coming from MongoDB, it fails without a specific error message :

```
      gateway.subscription.create({
        id: '56d48f8b2eeb856d0219f52b', // Inlined for example
        merchantAccountId: 'whatever',
        planId: 'pwhatever',
        paymentMethodToken: paymentMethodToken,
        price: '10.00',
        numberOfBillingCycles: 5
      },cb);

// Fails with :

TypeError: Cannot read property 'apiErrorResponse' of undefined
    at /src/node_modules/braintree/lib/braintree/gateway.js:23:19
    at /src/node_modules/braintree/lib/braintree/http.js:103:20
    at Parser.<anonymous> (/src/node_modules/braintree/node_modules/xml2js/lib/xml2js.js:138:18)
    at Parser.EventEmitter.emit (events.js:107:17)
    at Object.saxParser.onerror (/src/node_modules/braintree/node_modules/xml2js/lib/xml2js.js:51:24)
    at emit (/src/node_modules/braintree/node_modules/xml2js/node_modules/sax/lib/sax.js:625:33)
    at error (/src/node_modules/braintree/node_modules/xml2js/node_modules/sax/lib/sax.js:654:3)
    at strictFail (/src/node_modules/braintree/node_modules/xml2js/node_modules/sax/lib/sax.js:675:22)
    at Object.write (/src/node_modules/braintree/node_modules/xml2js/node_modules/sax/lib/sax.js:1020:11)
    at Parser.exports.Parser.Parser.parseString (/src/node_modules/braintree/node_modules/xml2js/lib/xml2js.js:145:29)
```

However, prepending a letter to the id works correctly. Maybe it's documented somewhere that the ID should not start with a number, for sure not in Subscription.create reference : https://developers.braintreepayments.com/reference/request/subscription/create/node 

Apart from the missing documentation, maybe the error should be handled better than with an unrecoverable exception.

**Comment by matthewarkin** [comment] 2016-02-29 20:24
Hi @SimoneGianni I just tried to reproduce this, an passing `56d48f8b2eeb856d0219f52b` as a string I cannot reproduce it.  I can reproduce it when pass it as a mongo ObjectId (since those are not actually strings). You'll want to call `.toHexString()` on the ObjectId to covert it to a string and that should work.

**Comment by pblesi** [comment] 2016-03-08 17:57
I am closing this issue. Feel free to reopen it if your issue still persists.

**Closed by pblesi** 2016-03-08 17:57 UTC
