### ISSUE TITLE
Issues with 0.10.34

### ISSUE THREAD

**Issue by timewarrior** [braintree/braintree_node#44] opened 2014-12-18 13:43 UTC
Hi
I was just trying braintree with the Nodejs version which got released yesterday (0.10.34). Trying to generate a client token leads to "Unexpected" error. I rollbacked to 0.10.33 and things work great. Thought this is something you might want to look at.

Thanks

**Comment by raymondberg** [comment] 2015-05-19 19:51
@timewarrior, closing this as a duplicate of the issue @openbl referenced. Please feel free to reopen if needed.

**Closed by raymondberg** 2015-05-19 19:51 UTC
