### ISSUE TITLE
TypeError: Cannot read property 'baseUrl' of undefined

### ISSUE THREAD

**Issue by tschiela** [braintree/braintree_node#58] opened 2015-10-05 05:27 UTC
If I try to run that piece of code:
```javascript
var gateway = braintree.connect({
  environment: braintree.Environment[config.braintree.environment],
  merchantId: config.braintree.merchantId,
  publicKey: config.braintree.publicKey,
  privateKey: config.braintree.privateKey
});

module.exports.gateway = gateway;
```

I got a TypeError:

```
TypeError: Cannot read property 'baseUrl' of undefined
    at Config.baseUrl (***/node_modules/braintree/lib/braintree/config.js:36:28)
    at Config.baseMerchantUrl (***/node_modules/braintree/lib/braintree/config.js:40:17)
    at new TransparentRedirectGateway (***/node_modules/braintree/lib/braintree/transparent_redirect_gateway.js:39:34)
    at new BraintreeGateway (***/node_modules/braintree/lib/braintree/braintree_gateway.js:69:32)
    at Object.connect (***/node_modules/braintree/lib/braintree.js:42:10)
    at Object.<anonymous> (***/helper/braintree.js:10:25)
```

Any ideas on that?

**Comment by NickTomlin** [comment] 2015-10-05 17:33
This typically is because the environment you passed into `braintree.connect` is undefined, which will throw an error when we attempt to access its `baseUrl` in [config.coffee](https://github.com/
braintree/braintree_node/blob/master/src/braintree/config.coffee#L25):

```coffeescript
  baseUrl: -> @environment.baseUrl()
```

Are you sure that `config.braintree.environment` corresponds to a valid Braintree environment (`Sandbox` or `Production`)? Please let us know if that doesn't resolve your issue. Thanks!

**Comment by ryanjpodonnell** [comment] 2015-10-23 18:08
I'm going to go ahead and close this issue for now. If you are still having issues, feel free to re-open.

**Closed by ryanjpodonnell** 2015-10-23 18:08 UTC

**Comment by Gardezi1** [comment] 2017-07-19 06:03
@tschiela  were you able to solve this problem. If yes then how.

**Comment by sidonaldson** [comment] 2017-11-13 10:48
To anyone else who came across this issue. I had to change the environment property to load from `braintree.Environment.Sandbox` rather than passing in `"Sandbox"`

```
braintree.connect({
    environment: braintree.Environment.Sandbox,
    merchantId: process.env.BT_MERCHANT_ID,
    publicKey: process.env.BT_PUBLIC_KEY,
    privateKey: process.env.BT_PRIVATE_KEY
})

```

**Comment by moshebeeri** [comment] 2018-01-03 08:09
The issue is that the example shows the 'good practice' way of working with environment variables,
while hiding the API requirements for:
braintree.Environment.Sandbox
or
braintree.Environment['Sandbox']

**Comment by moshebeeri** [comment] 2018-01-03 08:24
```
////////////////////////////////////////////////
//// see: https://github.com/braintree/braintree_express_example/blob/master/routes/index.js

let braintree = require('braintree');
let gateway;

//require('dotenv').load(); process.env.BT_MERCHANT_ID;
//environment = process.env.BT_ENVIRONMENT.charAt(0).toUpperCase() + process.env.BT_ENVIRONMENT.slice(1);

gateway = braintree.connect({
  environment: braintree.Environment.Sandbox, //braintree.Environment['Sandbox']
  merchantId: 'VVVVV',
  publicKey: 'XXXXX',
  privateKey: 'CCCCC'
});


let TRANSACTION_SUCCESS_STATUSES = [
  braintree.Transaction.Status.Authorizing,
  braintree.Transaction.Status.Authorized,
  braintree.Transaction.Status.Settled,
  braintree.Transaction.Status.Settling,
  braintree.Transaction.Status.SettlementConfirmed,
  braintree.Transaction.Status.SettlementPending,
  braintree.Transaction.Status.SubmittedForSettlement
];


function formatErrors(errors) {
  let formattedErrors = '';

  for (let i in errors) { // eslint-disable-line no-inner-declarations, vars-on-top
    if (errors.hasOwnProperty(i)) {
      formattedErrors += 'Error: ' + errors[i].code + ': ' + errors[i].message + '\n';
    }
  }
  return formattedErrors;
}

function createResultObject(transaction) {
  let result;
  let status = transaction.status;

  if (TRANSACTION_SUCCESS_STATUSES.indexOf(status) !== -1) {
    result = {
      header: 'Sweet Success!',
      icon: 'success',
      message: 'Your test transaction has been successfully processed. See the Braintree API response and try again.'
    };
  } else {
    result = {
      header: 'Transaction Failed',
      icon: 'fail',
      message: 'Your test transaction has a status of ' + status + '. See the Braintree API response and try again.'
    };
  }

  return result;
}

// GET /checkouts/new
exports.checkouts_new = function (req, res) {
  gateway.clientToken.generate({}, function (err, response) {
    if(err) return handleError(res, err);
    return res.status(200).json({clientToken: response.clientToken});
  });
};

// GET /checkouts/:id
exports.checkouts_id = function (req, res) {
  let result;
  let transactionId = req.params.id;

  gateway.transaction.find(transactionId, function (err, transaction) {
    if(err) return handleError(res, err);
    result = createResultObject(transaction);
    return res.status(200).json({transaction: transaction, result: result});

  });
};

// POST /checkouts
exports.checkouts = function (req, res) {
  let transactionErrors;
  let amount = req.body.amount; // In production you should not take amounts directly from clients
  let nonce = req.body.payment_method_nonce;

  gateway.transaction.sale({
    amount: amount,
    paymentMethodNonce: nonce,
    options: {
      submitForSettlement: true
    }
  }, function (err, result) {
    if (result.success || result.transaction) {
      res.redirect('/' + result.transaction.id);
    } else {
      transactionErrors = result.errors.deepErrors();
      //req.flash('error', {msg: formatErrors(transactionErrors)});
      res.redirect('/new');
    }
  });
};
//////////////////////////
```

**Comment by moshebeeri** [comment] 2018-01-03 08:28
`////////////////////////////////////////////////
//// see: https://github.com/braintree/braintree_express_example/blob/master/routes/index.js

let braintree = require('braintree');
let gateway;

//require('dotenv').load(); process.env.BT_MERCHANT_ID;
//environment = process.env.BT_ENVIRONMENT.charAt(0).toUpperCase() + process.env.BT_ENVIRONMENT.slice(1);

gateway = braintree.connect({
  environment: braintree.Environment.Sandbox, //braintree.Environment['Sandbox']
  merchantId: 'hhk8bks2bxdrp7jm',
  publicKey: 'f7dt4jczwvx2vkxg',
  privateKey: '265da49809261f3bbafe1ab8068cae62'
});


let TRANSACTION_SUCCESS_STATUSES = [
  braintree.Transaction.Status.Authorizing,
  braintree.Transaction.Status.Authorized,
  braintree.Transaction.Status.Settled,
  braintree.Transaction.Status.Settling,
  braintree.Transaction.Status.SettlementConfirmed,
  braintree.Transaction.Status.SettlementPending,
  braintree.Transaction.Status.SubmittedForSettlement
];


function formatErrors(errors) {
  let formattedErrors = '';

  for (let i in errors) { // eslint-disable-line no-inner-declarations, vars-on-top
    if (errors.hasOwnProperty(i)) {
      formattedErrors += 'Error: ' + errors[i].code + ': ' + errors[i].message + '\n';
    }
  }
  return formattedErrors;
}

function createResultObject(transaction) {
  let result;
  let status = transaction.status;

  if (TRANSACTION_SUCCESS_STATUSES.indexOf(status) !== -1) {
    result = {
      header: 'Sweet Success!',
      icon: 'success',
      message: 'Your test transaction has been successfully processed. See the Braintree API response and try again.'
    };
  } else {
    result = {
      header: 'Transaction Failed',
      icon: 'fail',
      message: 'Your test transaction has a status of ' + status + '. See the Braintree API response and try again.'
    };
  }

  return result;
}

// GET /checkouts/new
exports.checkouts_new = function (req, res) {
  gateway.clientToken.generate({}, function (err, response) {
    if(err) return handleError(res, err);
    return res.status(200).json({clientToken: response.clientToken});
  });
};

// GET /checkouts/:id
exports.checkouts_id = function (req, res) {
  let result;
  let transactionId = req.params.id;

  gateway.transaction.find(transactionId, function (err, transaction) {
    if(err) return handleError(res, err);
    result = createResultObject(transaction);
    return res.status(200).json({transaction: transaction, result: result});

  });
};

// POST /checkouts
exports.checkouts = function (req, res) {
  let transactionErrors;
  let amount = req.body.amount; // In production you should not take amounts directly from clients
  let nonce = req.body.payment_method_nonce;

  gateway.transaction.sale({
    amount: amount,
    paymentMethodNonce: nonce,
    options: {
      submitForSettlement: true
    }
  }, function (err, result) {
    if (result.success || result.transaction) {
      res.redirect('' + result.transaction.id);
    } else {
      transactionErrors = result.errors.deepErrors();
      //req.flash('error', {msg: formatErrors(transactionErrors)});
      res.redirect('new');
    }
  });
};
//////////////////////////`
