### ISSUE TITLE
Deno Braintree

### ISSUE THREAD

**Issue by do4Mother** [braintree/braintree_node#218] opened 2023-01-26 01:27 UTC
### General information

- SDK/Library version: 3.13.0
- Environment: Sandbox
- Language, language version, and OS: Supabase

### Issue description

i'm having trouble integrating Braintree payments using Deno. When I try to create a transaction with a payment method and create a customer. I get an error from the log like this.

```
TypeError: B.setTimeout is not a function
    at https://esm.sh/v104/braintree@3.13.0/X-ZHN2LzAuMTMyLjA/deno/braintree.js:2:11960
    at new Promise (<anonymous>)
    at Je.httpRequest (https://esm.sh/v104/braintree@3.13.0/X-ZHN2LzAuMTMyLjA/deno/braintree.js:2:11184)
    at Je.<anonymous> (https://esm.sh/v104/@braintree/wrap-promise@2.1.0/X-ZHN2LzAuMTMyLjA/deno/wrap-promise.js:2:1479)
    at Je.post (https://esm.sh/v104/braintree@3.13.0/X-ZHN2LzAuMTMyLjA/deno/braintree.js:2:10463)
    at Je.<anonymous> (https://esm.sh/v104/@braintree/wrap-promise@2.1.0/X-ZHN2LzAuMTMyLjA/deno/wrap-promise.js:2:1479)
    at Ur.create (https://esm.sh/v104/braintree@3.13.0/X-ZHN2LzAuMTMyLjA/deno/braintree.js:22:19972)
    at Ur.<anonymous> (https://esm.sh/v104/@braintree/wrap-promise@2.1.0/X-ZHN2LzAuMTMyLjA/deno/wrap-promise.js:2:1479)
    at Ur.sale (https://esm.sh/v104/braintree@3.13.0/X-ZHN2LzAuMTMyLjA/deno/braintree.js:22:20894)
    at Ur.<anonymous> (https://esm.sh/v104/@braintree/wrap-promise@2.1.0/X-ZHN2LzAuMTMyLjA/deno/wrap-promise.js:2:1479)
```

and here it's my source code

```
import braintree from "https://esm.sh/braintree@3.13.0?target=deno&no-check";

export const gateway = new braintree.BraintreeGateway({
  environment: braintree.Environment.Sandbox,
  merchantId: Deno.env.get("BRAINTREE_MERCHANT_ID") ?? "",
  publicKey: Deno.env.get("BRAINTREE_PUBLIC_KEY") ?? "",
  privateKey: Deno.env.get("BRAINTREE_PRIVATE_KEY") ?? "",
});
```

```
const result = await gateway.transaction.sale({
        amount: "10",
        customer: {
          id: user.id,
          email: user.email ?? "",
        },
        paymentMethodNonce: nonce,
        deviceData: deviceData,
      });
```

**Comment by hollabaq86** [comment] 2023-01-26 15:11
👋 @do4Mother I believe the root of the issue is that Deno is `a modern runtime for JavaScript and TypeScript`, and this library doesn't support Typescript yet (see #176).

Since we don't develop the Deno library, we can't really offer much support, but maybe the [Deno](https://github.com/denoland/deno) community might be able to offer some help for interacting with libraries that don't yet have Typescript support. I did see they have a `--no-check` [option](https://deno.land/manual@v1.4.1/getting_started/typescript#--no-check-option) in their docs that might skip type checking.

I'm going to close this issue since we're tracking the root cause (Typescript support) in the issue previously mentioned.

**Closed by hollabaq86** 2023-01-26 15:11 UTC

**Comment by crookedneighbor** [comment] 2023-01-26 17:18
My guess is that Deno's version of the http/https modules don't include a `setTimeout` function. https://github.com/braintree/braintree_node/blob/451e665f3a87de88f99281db225f0d9b99cbe33a/lib/braintree/http.js#L4-L5

**Comment by crookedneighbor** [comment] 2023-01-26 17:19
https://github.com/braintree/braintree_node/blob/451e665f3a87de88f99281db225f0d9b99cbe33a/lib/braintree/http.js#L187
